name: C++ CI

on:
  push:
    branches:
      - master  # trigger on push to master branch
  pull_request:
    branches:
      - master  # trigger on pull requests to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm test

    - uses: actions/checkout@v2  # Checkout the repository content to the runner
    
    - name: Clear GitHub Actions cache
      run: |
        npm cache clean --force
        yarn cache clean
        rm -rf ~/.npm
        rm -rf ~/.yarn

    - name: Install g++
      run: |
        sudo apt-get update  
        sudo apt-get install g++ libgtest-dev libsfml-dev cmake xvfb
    
    - name: Test
      run: |
        make test

    - name: Build
      run: |
        make

