name: C++ CI

on:
  push:
    branches:
      - master  # trigger on push to master branch
  pull_request:
    branches:
      - master  # trigger on pull requests to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checkout the repository content to the runner

    - name: Install g++
      run: |
        sudo apt-get update  
        sudo apt-get install g++ libgtest-dev libsfml-dev cmake
    
    - name: Test
      run: |
        make test

    - name: Build
      run: |
        make


